# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc/calc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calc/calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61lc/calc.proto\x12\ncalculator\"2\n\x08\x46raction\x12\x11\n\tnumerator\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65nominator\x18\x02 \x01(\x05\"e\n\x11\x46ractionOpRequest\x12\'\n\tfraction1\x18\x01 \x01(\x0b\x32\x14.calculator.Fraction\x12\'\n\tfraction2\x18\x02 \x01(\x0b\x32\x14.calculator.Fraction\"8\n\x10\x46ractionResponse\x12$\n\x06result\x18\x01 \x01(\x0b\x32\x14.calculator.Fraction2\xa5\x03\n\nCalculator\x12\x42\n\x03\x41\x64\x64\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponse\x12\x42\n\x03Sub\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponse\x12\x43\n\x04Mult\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponse\x12\x42\n\x03\x44iv\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponse\x12\x42\n\x03Max\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponse\x12\x42\n\x03Min\x12\x1d.calculator.FractionOpRequest\x1a\x1c.calculator.FractionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc.calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRACTION']._serialized_start=31
  _globals['_FRACTION']._serialized_end=81
  _globals['_FRACTIONOPREQUEST']._serialized_start=83
  _globals['_FRACTIONOPREQUEST']._serialized_end=184
  _globals['_FRACTIONRESPONSE']._serialized_start=186
  _globals['_FRACTIONRESPONSE']._serialized_end=242
  _globals['_CALCULATOR']._serialized_start=245
  _globals['_CALCULATOR']._serialized_end=666
# @@protoc_insertion_point(module_scope)
